// <auto-generated />
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Inventory = 13,
                            Price = 7.5,
                            ProductName = "Vanilla Ice Cream"
                        },
                        new
                        {
                            ProductID = 2,
                            Inventory = 7,
                            Price = 8.1500000000000004,
                            ProductName = "Mango Ice Cream"
                        },
                        new
                        {
                            ProductID = 3,
                            Inventory = 20,
                            Price = 8.0,
                            ProductName = "Strawberry Ice Cream"
                        },
                        new
                        {
                            ProductID = 4,
                            Inventory = 20,
                            Price = 8.5,
                            ProductName = "Chocolate Ice Cream"
                        },
                        new
                        {
                            ProductID = 5,
                            Inventory = 8,
                            Price = 8.75,
                            ProductName = "Peanut Butter Ice Cream"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
